### ISSUE TITLE
[Error report] baselines.common.tf_util functions

### ISSUE THREAD

**Issue by Sungtae-Lee** [Silvicek/distributional-dqn#3]
baselines.common.tf_util seems like it has no attribute 'ensure_tf_input' and 'BatchInput'
Any solutions?

**Comment by Silvicek** [comment]
Hi, as mentioned in the installation guide you have to use the older baselines version in my fork  https://github.com/Silvicek/baselines my guess is you have a newer version of baselines which isn't backward compatible.
